name: easy_ledger
version: 1.0.0+1
publish_to: none
description: 一个跨端记账软件
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  bitsdojo_window: ^0.1.5
  shared_preferences: ^2.2.3
  screen_go: ^1.1.6
  sidebarx: ^0.17.1
  ionicons: ^0.2.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
